### ISSUE TITLE
Mismatch in scripting docs between expected and actual output

### ISSUE THREAD

**Issue by fasiha** [jgm/pandoc-website#10]
I [asked](https://groups.google.com/d/topic/pandoc-discuss/doSgVBKYPV4/discussion) on the mailing list to confirm but there’s a small error in the [Scripting](http://pandoc.org/scripting.html#a-simple-example) docs: the output of `pandoc -t native test.txt` will not contain metadata, it needs the `-s` flag.

I will submit a PR.

**Comment by jgm** [comment]
Sorry!  I only saw your PR after manually making the change myself.

**Comment by jgm** [comment]
Thank you for taking the time to do this.
