### ISSUE TITLE
try pandoc: allow back and forth conversion

### ISSUE THREAD

**Issue by colemickens** [jgm/pandoc-website#26]
Hello, someone recommended the "Try Pandoc" site as an easy way to author MediaWiki page in Markdown.

I was curious if it would be possible (or accepted?) to change the page to both directions (as separate buttons), instead of the conversion only going one direction? Thanks.

**Comment by jgm** [comment]
I'd rather keep it simple.  The point is to demonstrate pandoc, and it's easier if the results are always on the right-hand side, under the example command.

**Comment by colemickens** [comment]
Okay, thanks!
