### ISSUE TITLE
Detect OS and generate download link

### ISSUE THREAD

**Issue by mb21** [jgm/pandoc-website#29]
I wrote the following JavaScript to progressively enhance the download link button.

It tries to detect the OS and find the latest pandoc release URL via the GitHub REST API. If the JS fails for some reason, the fallback would be the current button.

Only later did I [realize that for](https://developer.github.com/v3/#rate-limiting):

> unauthenticated requests, the rate limit allows for [only] up to 60 requests per hour. 

So we would have to construct the download URL when we generate the static site. Possibly with a lua filter?

Hope this is useful..

```javascript
(function() {
  // from https://stackoverflow.com/a/38241481/214446
  var userAgent = window.navigator.userAgent
    , platform = window.navigator.platform
    , macosPlatforms = ['Macintosh', 'MacIntel']
    , windowsPlatforms = ['Win32', 'Win64', 'Windows', 'WinCE']
    , iosPlatforms = ['iPhone', 'iPad', 'iPod']
    , target = null
    , detected
    ;
  if (macosPlatforms.indexOf(platform) !== -1) {
    detected = 'macOS';
    target = '-macOS.pkg';
  } else if (iosPlatforms.indexOf(platform) !== -1) {
  } else if (windowsPlatforms.indexOf(platform) !== -1) {
    if (userAgent.indexOf("WOW64") !== -1 || userAgent.indexOf("Win64") !== -1){
      // from https://stackoverflow.com/a/6866569/214446
      detected = 'Windows (64-bit)';
      target = '-windows-x86_64.msi';
    } else {
      detected = 'Windows (32-bit)';
      target = '-windows-i386.msi';
    }
  } else if (/Android/.test(userAgent)) {
  } else if (!os && /Linux/.test(platform)) {
    detected = 'Linux (64-bit)';
    target = '-amd64.deb';
  }

  if (target) {
    fetch("https://api.github.com/repos/jgm/pandoc/releases")
    .then(function(data) {
        return data.json();
    })
    .then(function(json) {
      var assets = json[0].assets.filter(function(a){
        return a.name.endsWith(target)
      });
      if (assets[0]) {
        var btn = document.getElementById('download-btn');
        btn.setAttribute('href', assets[0].browser_download_url);
        btn.innerHTML += 'detected ' + detected;
      }
    });
  }
})();
```

**Comment by jgm** [comment]
Why would the rate limiting be a problem?  I assume
the limit is for requests from a given IP, not
requests originating on a given web page.  So unless
someone wants to download pandoc 60 times in a row,
this should be fine -- or am I missing something?

**Comment by mb21** [comment]
Ah yes, of course. I confused the authenticated and unauthenticated requests...

I can make a pull... what's the best way to load this js only on the /installing.html page?

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> I can make a pull... what's the best way to load this js only on the /installing.html page?

Hm.  Maybe change the Makefile to use
--include-in-header when generating installing.html?
