### ISSUE TITLE
"installing from source" procedure should include package names

### ISSUE THREAD

**Issue by unixpipecentipede** [jgm/pandoc-website#4]
Hello. It seems `installing.txt` should say:

    stack setup
    stack install pandoc [pandoc-citeproc]

**Comment by jgm** [comment]
installing.txt gives instructions for building from
source code downloaded from a tarball or the
repo.  These instructions are correct; they
presuppose you're in the source directory.

If you're not, the commands you give will work,
but you'll get the latest version in Stackage.

+++ unixpipecentipede [Sep 03 16 08:58 ]:

**Comment by unixpipecentipede** [comment]
Ohh I seee. Each heading is a *step*! No problem then. Thank you!
