### ISSUE TITLE
TOC is not more placed on the right

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc-website#55]
With the new website (following  I guess ) 

I noticed a few change probably undesired. Here is one

Now I get this: 
![image](https://user-images.githubusercontent.com/6791940/144851162-a6fa3638-1bcb-418c-a538-9fe8812e4395.png)

with the TOC being at the end after footnote
![image](https://user-images.githubusercontent.com/6791940/144851247-8e65ce8e-7cf2-4a12-aad1-1874e4d9141f.png)

This is probably something with the bootstrap grid system. Maybe because of the margins
![image](https://user-images.githubusercontent.com/6791940/144851467-668d0690-eef4-45e2-8482-a1643224c8a0.png)
Which make the 2 element in row to be too large despite `col-md-3` and `col-md-9` being 12 width. 
If I remove the margin
![image](https://user-images.githubusercontent.com/6791940/144851875-22181c61-6c17-485c-ab53-88122e00bdb4.png)

I correctly get the TOC on the right
![image](https://user-images.githubusercontent.com/6791940/144851950-16af44c9-1f79-406e-a6a3-fe79aa44ad36.png)

It may not be the underlying issue but could be related.

**Comment by jgm** [comment]
Looks like you're still using the old CSS (probably cached).
Visit https://pandoc.org/css/screen.css and refresh?

There's probably something  I should be doing to ensure that when CSS changes, the old cached CSS is not used -- let me know if you have ideas about that.

**Comment by jgm** [comment]
I'm going to put a dated query string on the URL to encourage the browser to uncache it.

**Comment by cderv** [comment]
That was indeed the cause. I though using F5 or CTRL + R in the browser would reload the page after clearing the cache but it did not. Visiting the page and refresh as you advice have worked. 

For reference, after a search it seems it is CTRL + F5 to hard reload the page. 
Sorry for the noise in the issue board. 

> There's probably something I should be doing to ensure that when CSS changes, the old cached CSS is not used -- let me know if you have ideas about that.

And your last comment was what I would have suggested.
