### ISSUE TITLE
Anchor links on header are no more visible

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc-website#56]
The anchor that were added quite recently (#50) are placed on the left but no more shown now

![image](https://user-images.githubusercontent.com/6791940/144852567-a570b5cc-d5c4-4857-b89d-7bf47ef30fa9.png)

Maybe because there is less room on the left than before (I remember previous version of MANUAL was centered so more room on the left). 

Probably some CSS tweaks to do, or place the anchor link on the right after header instead ?

**Comment by jgm** [comment]
See my comment on the other issue.
You are probably using old cached CSS.

**Comment by cderv** [comment]
yes that was it. Now I know how to _really_ hard reload a page. Sorry for the noise.
