### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by khalid-hussain** [jgm/pandoc-website#7]
I want to use the HTML template from this repository but I could not find a license. What are the terms and conditions if I want to reuse parts of the repository?

Thanks for your time.

**Comment by oxr463** [comment]
Here is what I found:

```
# Authors

Copyright 2006--2020 John MacFarlane (jgm@berkeley.edu). Released
under the [GPL], version 2 or greater.  This software carries no
warranty of any kind.  (See COPYRIGHT for full copyright and
warranty notices.) For a full list of contributors, see the file
AUTHORS.md in the pandoc source code.
```

Source: https://github.com/jgm/pandoc-website/blob/master/MANUAL.txt#L5897

I agree though, further clarification is needed since it is unclear whether this license covers the contents of the website in addition to the actual source code of pandoc itself.

**Comment by jgm** [comment]
The GPL2 license covers pandoc's source code and the documentation in the pandoc repository.
Items that appear on the website but not in the pandoc repository are not covered by that license and should thus be treated like any other copyrighted material.
